---
- name: Shutdown AAP VMs
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Shutdown VMs based on tag filters
      amazon.aws.ec2_instance:
        state: stopped
        filters:
          "tag:deployment": "aap-infrastructure-{{ deployment_id }}"
          "instance-state-name":
            - pending
            - running
        region: "{{ infrastructure_region }}"
